pipeline {
    agent any

    environment {
        IMAGE_NAME = "backend-container"
        CONTAINER_NAME = "backend-container"
        PORT = "8080"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Backend JAR') {
            steps {
                dir('backend/aws-springboot-project') {
                    sh  'mvn clean install -Dmaven.test.skip=true'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend/aws-springboot-project') {
                    sh "docker build -t ${IMAGE_NAME}:latest ."
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                sh """
                docker stop ${CONTAINER_NAME} || true
                docker rm ${CONTAINER_NAME} || true
                """
            }
        }

        stage('Run Backend Container') {
            steps {
                withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AKIAYK6BVJL3B5ZHOKX2'),
                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: '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'),
                    string(credentialsId: 'AWS_REGION', variable: 'ap-south-1'),
                    string(credentialsId: 'COGNITO_USER_POOL_ID', variable: 'ap-south-1_oj0VrOvfN'),
                    string(credentialsId: 'COGNITO_CLIENT_ID', variable: '423p601m159b0c24hcc9tj0ogo'),
                    string(credentialsId: 'COGNITO_CLIENT_SECRET', variable: 'qqkk2av2ln5rtd2k6l2f1jaf799v43qjnt9v0ucl3pmn57pgaa3')
                ]) {
                    sh """
                    docker run -d \
                    --name ${CONTAINER_NAME} \
                    --network aws-network \
                    -p ${PORT}:8080 \
                    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                    -e AWS_REGION=$AWS_REGION \
                    -e COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID \
                    -e COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID \
                    -e COGNITO_CLIENT_SECRET=$COGNITO_CLIENT_SECRET \
                     ${IMAGE_NAME}:latest
                     """
                   }
               }
        }

    }

    post {
        success {
            echo "✅ Backend deployed successfully"
        }
        failure {
            echo "❌ Backend deployment failed"
        }
    }
}

